
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-deployment
spec:
  selector:
    matchLabels:
      app: argroups
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: argroups
    spec:
      containers:
      - name: argroups
        image: sarangarao/sxb-react-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8060
        
---
kind: Service
apiVersion: v1
metadata:
 name: argroups
spec:
 type: NodePort
 ports:
 - port: 80
 targetPort: 80
 protocol: TCP

