
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: sarangarao/sxb-react-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
kind: Service
apiVersion: v1
metadata:
   name: demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 32000
  selector:
    app: demo
