apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: argroups 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argroups 
  template:
    metadata:
      labels:
        app: argroups 
    spec:
      containers:
      - name: argroups 
        image: 328651874878.dkr.ecr.ap-south-1.amazonaws.com/argroups:latest
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: java-microservice-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer 
  selector:
    app: argroups 
  ports:
  - protocol: TCP
    port: 8060
    targetPort: 8060
