
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-deployment
spec:
  selector:
    matchLabels:
      app: argroups
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: argroups
    spec:
      containers:
      - name: argroups
        image: 328651874878.dkr.ecr.ap-south-1.amazonaws.com/argroups:latest
        ports:
        - containerPort: 8060

